<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);WFO1000</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="jeux.Tests\**\*.cs" />
    <None Remove="jeux.Tests\**\*" />
    <Content Remove="jeux.Tests\**\*" />
    <Compile Remove="_archive\**\*" />
    <None Remove="_archive\**\*" />
    <Content Remove="_archive\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
